/// Embedded scaffold files for `pidgn new`.
/// Each file lives under pidgn_cli/scaffold/ as a real, editable file.
const std = @import("std");

// ── Build ────────────────────────────────────────────────────────────
pub const build_zig = @embedFile("../scaffold/build.zig");

// ── Main variants ────────────────────────────────────────────────────
pub const main_zig = @embedFile("../scaffold/base/main.zig");
pub const main_zig_full = @embedFile("../scaffold/full/main.zig");
pub const main_zig_api = @embedFile("../scaffold/api/main.zig");

// ── Controllers (full mode) ──────────────────────────────────────────
pub const home_controller_zig = @embedFile("../scaffold/full/controllers/home.zig");
pub const api_controller_zig = @embedFile("../scaffold/full/controllers/api.zig");

// ── Templates (full mode) ────────────────────────────────────────────
pub const layout_html_pidgn = @embedFile("../scaffold/full/templates/layout.html.pidgn");
pub const home_html_pidgn = @embedFile("../scaffold/full/templates/home.html.pidgn");

// ── Config (base) ────────────────────────────────────────────────────
pub const config_zig = @embedFile("../scaffold/config/base/config.zig");
pub const config_dev_zig = @embedFile("../scaffold/config/base/dev.zig");
pub const config_prod_zig = @embedFile("../scaffold/config/base/prod.zig");
pub const config_staging_zig = @embedFile("../scaffold/config/base/staging.zig");

// ── Config (db-aware) ────────────────────────────────────────────────
pub const config_zig_db = @embedFile("../scaffold/config/db/config.zig");
pub const config_dev_zig_db = @embedFile("../scaffold/config/db/dev.zig");
pub const config_prod_zig_db = @embedFile("../scaffold/config/db/prod.zig");
pub const config_staging_zig_db = @embedFile("../scaffold/config/db/staging.zig");

// ── Env files ────────────────────────────────────────────────────────
pub const dot_env = @embedFile("../scaffold/env/base/.env");
pub const env_example = @embedFile("../scaffold/env/base/.env.example");
pub const dot_env_postgres = @embedFile("../scaffold/env/postgres/.env");
pub const env_example_postgres = @embedFile("../scaffold/env/postgres/.env.example");
pub const dot_env_sqlite = @embedFile("../scaffold/env/sqlite/.env");
pub const env_example_sqlite = @embedFile("../scaffold/env/sqlite/.env.example");

// ── Static assets ────────────────────────────────────────────────────
pub const gitignore = @embedFile("../scaffold/.gitignore.tmpl");
pub const style_css = @embedFile("../scaffold/style.css");

// ── Docker ───────────────────────────────────────────────────────────
pub const dockerfile = @embedFile("../scaffold/docker/base/Dockerfile");
pub const docker_compose_yml = @embedFile("../scaffold/docker/base/docker-compose.yml");
pub const dockerignore = @embedFile("../scaffold/docker/base/.dockerignore");
pub const docker_compose_yml_postgres = @embedFile("../scaffold/docker/postgres/docker-compose.yml");

// ── build.zig.zon (generated, not embedded) ──────────────────────────

pub fn buildZigZon(name: []const u8, buf: []u8) ?[]const u8 {
    // Sanitize name for use as a Zig identifier (replace dots/hyphens with underscores)
    var ident_buf: [128]u8 = undefined;
    const ident_len = @min(name.len, ident_buf.len);
    for (0..ident_len) |i| {
        ident_buf[i] = if (std.ascii.isAlphanumeric(name[i]) or name[i] == '_') name[i] else '_';
    }
    const ident = ident_buf[0..ident_len];

    // Fingerprint is omitted here — it must be generated by `zig build`
    // after the project is created. See new.zig patchFingerprint().
    return std.fmt.bufPrint(buf,
        \\.{{
        \\    .name = .{s},
        \\    .version = "0.1.0",
        \\    .fingerprint = 0x0000000000000000,
        \\    .minimum_zig_version = "0.16.0-dev.2535+b5bd49460",
        \\    .dependencies = .{{
        \\        .pidgn = .{{
        \\            .url = "git+https://github.com/seemsindie/pidgn#84f319f8ece0311e6405229a59645f17430394f4",
        \\            .hash = "pidgn-0.3.1-beta.16-0tg_skRrCQDnYnRB1p4EhBxJ5KPZsPVgOJ40ZcUoEUny",
        \\        }},
        \\    }},
        \\    .paths = .{{
        \\        "build.zig",
        \\        "build.zig.zon",
        \\        "src",
        \\        "config",
        \\    }},
        \\}}
        \\
    , .{ident}) catch null;
}
